version: 1.0.{build}
os: Visual Studio 2017
platform: x64
shallow_clone: true
branches:
  only:
    - master
environment:
  matrix:
  - config: Debug
before_build:
  - cmake -DCMAKE_BUILD_TYPE=%config% -DGEOTOOLS_BUILD_ON_TRAVIS=ON -G "Visual Studio 15 2017 Win64" .
build:
  parallel: true
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
